name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build --build-arg COMMIT_NAME="$(git log -1 --pretty=%B)" -t embassy_bot:latest .
      - name: Add private key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
         mkdir $HOME/.ssh/ && echo $SSH_KEY > $HOME/.ssh/id_rsa.pub
      - name: Push Docker image to home server
        env:
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          docker save embassy_bot:latest | ssh $SERVER_USER@$SERVER_NAME 'docker load'
      - name: Run container on home server
        env:
          SERVER_NAME: ${{ secrets.SERVER_NAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh $SERVER_NAME@$SERVER_HOST '
            docker stop embassy_bot || true &&
            docker rm embassy_bot || true &&
            docker run -d --env-file /envs/embassy_bot/.env --restart always --name embassy_bot embassy_bot:latest
          '
