name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build --build-arg COMMIT_NAME="$(git log -1 --pretty=%B)" -t embassy_bot:latest .
      - name: Add private key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh/ &&
          echo $SSH_KEY > ~/.ssh/id_rsa.pub &&
          cat <<< "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Push Docker image to home server
        env:
          SERVER: ${{ secrets.SERVER }}
        run: |
          docker save embassy_bot:latest | ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR $SERVER 'docker load'
      - name: Run container on home server
        env:
          SERVER: ${{ secrets.SERVER }}
        run: |
          ssh $SERVER '
            docker stop embassy_bot || true &&
            docker rm embassy_bot || true &&
            docker run -d --env-file /envs/embassy_bot/.env --restart always --name embassy_bot embassy_bot:latest
          '
